package com.anatomist.core.nativeimage;

import com.github.javaparser.metamodel.BaseNodeMetaModel;
import com.github.javaparser.metamodel.JavaParserMetaModel;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeSet;

/**
 * Build-time tool that emits GraalVM reachability-metadata registering every
 * JavaParser AST node class for full field reflection.
 *
 * <p>JavaParser's parse-time validators reflectively introspect every AST node
 * via {@code PropertyMetaModel.getValue()}, which calls
 * {@code Class.getDeclaredFields()}. Under native-image's closed-world model
 * only registered fields are visible, so without this metadata real-world code
 * crashes with {@code NoSuchFieldError} the moment a validator touches an
 * un-registered field.</p>
 *
 * <p>This is generated rather than registered via a {@code Feature} because the
 * metamodel's static node list is populated by a class initializer that is not
 * reliably visible to Feature code under {@code --initialize-at-build-time}.
 * Running on a normal JVM (where {@code getNodeMetaModels()} returns the full
 * set) keeps the output deterministic. Re-run after bumping the JavaParser
 * version:</p>
 *
 * <pre>{@code
 *   mvn -q compile
 *   java -cp target/classes:<javaparser-jars> \
 *       com.anatomist.core.nativeimage.AstReflectConfigGenerator \
 *       src/main/resources/META-INF/native-image/com.antcodes/anatomist-javaparser-ast/reachability-metadata.json
 * }</pre>
 */
public final class AstReflectConfigGenerator {

    private AstReflectConfigGenerator() {}

    public static void main(String[] args) throws IOException {
        if (args.length != 1) {
            System.err.println("usage: AstReflectConfigGenerator <output-json-path>");
            System.exit(2);
        }
        Path out = Path.of(args[0]);
        Files.createDirectories(out.getParent());
        String json = generate();
        Files.writeString(out, json, StandardCharsets.UTF_8);
        System.out.println("Wrote " + out + " for "
                + JavaParserMetaModel.getNodeMetaModels().size() + " AST node classes");
    }

    /** Produce the reachability-metadata JSON registering allDeclaredFields for
     *  every AST node class, sorted by type name for stable diffs. */
    static String generate() {
        TreeSet<String> types = new TreeSet<>();
        for (BaseNodeMetaModel m : JavaParserMetaModel.getNodeMetaModels()) {
            types.add(m.getType().getName());
        }
        List<String> entries = new ArrayList<>();
        for (String type : types) {
            entries.add("    {\n"
                    + "      \"type\": \"" + type + "\",\n"
                    + "      \"allDeclaredFields\": true\n"
                    + "    }");
        }
        return "{\n"
                + "  \"comment\": \"GENERATED by AstReflectConfigGenerator. Registers all "
                + "JavaParser AST node fields so the parse-time MetaModel validators work "
                + "under native-image. Re-run after bumping the JavaParser version.\",\n"
                + "  \"reflection\": [\n"
                + String.join(",\n", entries) + "\n"
                + "  ]\n"
                + "}\n";
    }
}
